name: CI/CD Pipeline for Teacher

on:
  push:
    branches:
      - deployment
    paths:
      - 'Teacher/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install --prefix Teacher/

    - name: Run tests
      run: npm test --prefix Teacher/

    - name: Build project
      run: npm run build --prefix Teacher/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/deployment'

    steps:
    - uses: actions/checkout@v2

    - name: Deploy to VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
          cd /var/www/stargleam/teacher
          git pull
          npm install --production --prefix Teacher/
          # Assuming the build directory is within the Teacher directory and needs to be moved to a specific path
          cp -r Teacher/build/* /var/www/stargleam/teacher/
          pm2 restart all